### ISSUE TITLE
Task items disappear when tasklist overflows

### ISSUE THREAD

**Issue by M4he** [worron/awesome-config#10]
## Issue

On a smaller screen, the `tasklist` may overflow if many applications are opened in the same `tag`. If more `task` widgets are added than the [center layout](https://github.com/worron/awesome-config/blob/db156e984c896e794d4c69f6991a29232269fb07/rc-colorless.lua#L138) allows in terms of width (i.e. the `tasklist` overflows), the `tasklist` disappears from the panel `wibox` completely (visually). Even if the the amount of `task` items is reduced by closing applications or changing the `tag`, it won't reappear. It only reappears again when Awesome is restarted. This can be reproduced infinitely on my setup.

### Reproduction

1. load the `rc-colorless` setup
2. keep starting different applications until the `tasklist` fills up completely (= there is no free space at the left and right side of the `tasklist`)
3. start even more applications

#### Expected outcome

- the `task` widgets are squished together horizontally (reducing their width), so that all fit in the `tasklist` together

#### Actual outcome

- the `task` widgets (and effectively the whole `tasklist`) visually disappear completely from the panel until Awesome is restarted

## Debugging

After trying to pin down the issue for a few hours, I've reached the conclusion that it the [layout trick to center the tasklist widget](https://github.com/worron/awesome-config/blob/db156e984c896e794d4c69f6991a29232269fb07/rc-colorless.lua#L137) may be the culprit. From my humble debugging attempts, I can conclude the following:

- the amount of `task` objects in the `tasklist` widget is still correctly updated
  - when the amount of applications changes (e.g. `tag` switch), the [amount of task objects](https://github.com/worron/redflat/blob/efda8375a0ad11d15ccd03ce5a274fa3ac615d02/widget/tasklist.lua#L352) added to the layout container is correct
  - thus, the `task` widgets themselves still exist after the issue occurs
- after the widgets visually disappear from the screen, their [fit](https://github.com/worron/redflat/blob/efda8375a0ad11d15ccd03ce5a274fa3ac615d02/gauge/tag/blue.lua#L73) and [draw](https://github.com/worron/redflat/blob/efda8375a0ad11d15ccd03ce5a274fa3ac615d02/gauge/tag/blue.lua#L83) functions are *not* called anymore
- when I replace the [`expand` property](https://github.com/worron/awesome-config/blob/db156e984c896e794d4c69f6991a29232269fb07/rc-colorless.lua#L139) or the [layout](https://github.com/worron/awesome-config/blob/db156e984c896e794d4c69f6991a29232269fb07/rc-colorless.lua#L138) entirely, the issue is fixed but the `tasklist` is obviously not centered anymore

Which is why my best guess is that it's an issue with the `wibox.layout.align.horizontal` layout.

## Potential fix

The only reliable way I managed to find to fix this while still keeping the `tasklist` centered, is to change the layout to `flex.horizontal` and wrap the `tasklist` into a `wibox.container.place`, like this:

	{ -- middle widget
		layout = wibox.layout.flex.horizontal,
		wibox.container.place(env.wrapper(tasklist[s], "tasklist")),
	},

However, the `wibox.container.place` was just added to Awesome v4.2, so it breaks compatibility with v4.0 and v4.1 sadly.
Maybe there is some other way to get the `tasklist` centered using containers/layouts from v4.0, but I'm still rather new to the whole framework so I can't come up with anything else currently.

## Setup

- Debian 9.2 (stretch) x64
- Awesome WM v4.2 (issue also happened on v4.0)
- `rc-colorless` config of your repo

**Comment by worron** [comment]
Thanks for such detailed report, amazing work.

To be honest I can't see the root of problem but just added some tricky code to make `wibox.layout.align` work right. Seem like it fixed now, you can test and report.

By the way, editing theme file you can correct widget sizes for better fit in different screen size.

**Comment by M4he** [comment]
Thank you for looking into this so quickly! I tested your fix, seems to work just as fine on my setup.
Good job finding this solution, much appreciated!
