### ISSUE TITLE
popup error

### ISSUE THREAD

**Issue by cr1ogen** [worron/awesome-config#12]
I have a error in awesome, but the words from popup windows is too big, and i cant see the error 
![2017-11-23-022332_3840x2160_scrot](https://user-images.githubusercontent.com/9537788/33185109-32ba3cc2-d05f-11e7-95f0-0c046b015249.png)
Debian sid
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
Thanks

**Comment by worron** [comment]
I personally use Xephyr for debugging, so I just set all notifications to certain size. Anyway this setting was disabled in mentioned commit, error message now should be readable.

**Comment by cr1ogen** [comment]
Thanks its work!! Sorry for the inconvenience, but a i have this error 
![2017-11-23-222723_3840x2160_scrot](https://user-images.githubusercontent.com/9537788/33191989-b69c1338-d09d-11e7-8777-52c547103fa0.png)

Im use color-less theme, but this happens with the others themes too.
Sorry for mi english

**Comment by worron** [comment]
Strange, error like this can happen if you are running lua <= 5.2. Try to add first line at the to your `rc.lua`
```lua
unpack = unpack or table.unpack
```

**Comment by cr1ogen** [comment]
Its Work!! Thank you!!
