### ISSUE TITLE
how to resize the widgets

### ISSUE THREAD

**Issue by abhikaith** [worron/awesome-config#17]
I choose colourless theme but the widgets are big comparing to my screen sorry i'm nobe in awesome can you please add full detail how to configure awesome to look like yours thanks

**Comment by abhikaith** [comment]
i want to resize title bar and desktop widgets how can i

**Comment by worron** [comment]
Widget appearance can be changed with theme file. For example for colorless config `themes/colorless/theme.lua` should be edited. Follow the widget names and section commentaries to find wanted variable. E.g. base titlebar height [is here](https://github.com/worron/awesome-config/blob/60228446cf37c32705aaf3d2cb8d2ebdb5abca0e/themes/colorless/theme.lua#L490).

Unfortunately there is no proper documentation for this config by now. If you want to find full list of style variables for certain widget I can only recommend check source code of this widget.

**Comment by abhikaith** [comment]
Thanks
