### ISSUE TITLE
 Иконка в quick laucnher widget

### ISSUE THREAD

**Issue by interact82** [worron/awesome-config#18]
Как добавить свою иконку приложения в  quick laucnher widget? Откуда виджет берёт иконки туда?

![unixmen](https://user-images.githubusercontent.com/17098432/37712037-b0557d60-2d23-11e8-9925-386685017287.png)

**Comment by worron** [comment]
Модуль `dfparser` парсит имеющиеся в системе desktop файлы создает словарь вида 'имя приложения' - 'иконка этого приложения из определенной темы'  (где 'имя приложения' это его команда на запуск). Пример настройки `dfparser` в файле темы
```lua
theme.service.dfparser = {
	desktop_file_dirs = {
		'/usr/share/applications/',
		'/usr/local/share/applications/',
		'~/.local/share/applications',
	},
	icons = {
		df_icon       = theme.homedir .. "/.icons/ACYLS/scalable/mimetypes/application-x-executable.svg",
		theme         = theme.homedir .. "/.icons/ACYLS",
		custom_only   = true,  -- использовать только иконки из этой темы
		scalable_only = true   -- использовать только иконки формата SVG
	}
}
```

В свою очередь `qlaunch` виджет ищет иконку в этом словаре (не вдаваясь в подробности, не всегда успешно, но работает для большинства программ). Можно также задать настройки `dfparser` отдельно для данного виджета там же в файле темы.
