### ISSUE TITLE
не запускается

### ISSUE THREAD

**Issue by ad1862** [worron/awesome-config#2]
не работает тема, авесом 3.5.6-r2, Генту, пакет x11-libs/gdk-pixbuf установлен, модули lain, redflat тоже установлены, конф rc-base.lua
файл .awesome-errors:

error while running function
stack traceback:
	[C]: in function 'assert'
	/usr/share/lua/5.1/lgi/namespace.lua:151: in function </usr/share/lua/5.1/lgi/namespace.lua:148>
	(tail call): ?
	/aaa/.config/awesome/redflat/gauge/svgbox.lua:22: in main chunk
	[C]: in function 'require'
	/aaa/.config/awesome/redflat/menu.lua:38: in main chunk
	[C]: in function 'require'
	/aaa/.config/awesome/redflat/init.lua:13: in function </aaa/.config/awesome/redflat/init.lua:11>
	/aaa/.config/awesome/rc.lua:151: in main chunk
error: /usr/share/lua/5.1/lgi/namespace.lua:151: Typelib file for namespace 'Gdk' (any version) not found
Failed to open connection to "session" message bus: Failed to connect to socket /tmp/dbus-znAWoHpfbK: Connection refused

**Comment by worron** [comment]
Проблемы с биндингами gtk, я не в курсе как это на генту организовано. Возможно [этот тред](http://lua.2524044.n2.nabble.com/Problem-installing-lgi-td7581141.html) будет полезен.

Для проверки:  `lua -e 'lgi = require("lgi") print(lgi.GdkPixbuf, lgi.Gdk)'` должно отрабатывать без ошибок.

**Comment by worron** [comment]
Сейчас добавил фикс, теперь при проблемах с gdk pixbuf оно должно запускаться без векторного маштабирования иконок.

**Comment by ad1862** [comment]
Ссылка помогла, тема запустилась.
Нужно выставить флаг "introspection" следующим пакетам и пересобрать их:
x11-libs/gtk+					introspection
x11-libs/gdk-pixbuf				introspection
dev-libs/atk					introspection

Вопросы по самой теме, наверное лучше офрмить отдельно. Потом, если всё настрою, сделаю ебилд со всеми зависимостями, флагами итд. А пока нужно как-то уменьшить размеры всех элементов, на моем экране 1366\768 всё в одну кучу наползает.

**Comment by worron** [comment]
Ну и отлично. Размеры абсолютно всех элементов можно задать в теме. Тут не так давно некто [уже подгонял тему под свой монитор](https://www.linux.org.ru/forum/desktop/12188604#comments), можно полистать эту тему.
