### ISSUE TITLE
Feature: Starting application under specific tag

### ISSUE THREAD

**Issue by LukaK** [worron/awesome-config#21]
Hello,
first thank You for maintaining the configuration. Currently in my workflow I have tags for specific type of work I do.

Do You think You will, in the future, add support for starting applications under specific tags?

**Comment by worron** [comment]
>starting applications under specific tags

Awesome WM has [rules](https://awesomewm.org/apidoc/libraries/awful.rules.html) to accomplish this out of the box. Have you any problem with that approach?

**Comment by LukaK** [comment]
I have used tables approach in my last config and it was ok.

I was wondering if You plan to add code in the official repository for easy configuration. I am not very familiar with Lua to add it myself.

**Comment by worron** [comment]
All the code is already added. For example in `rc-colorless.lua` you can see
```lua
-- Rules
-----------------------------------------------------------------------------------------------------------------------
local rules = require("colorless.rules-config") -- load file with rules configuration
rules:init({ hotkeys = hotkeys})
```
which means rules table can be found in `colorless/rules-config.lua`. Edit it according API link above.
For example to start Firefox app under the tag named 'Tag4'
```lua
	-- Build rules
	--------------------------------------------------------------------------------
	self.rules = {
		{
			rule       = {},
			properties = args.base_properties or self.base_properties
		},
		{
			rule_any   = args.floating_any or self.floating_any,
			properties = { floating = true }
		},
		{
			rule_any   = { type = { "normal", "dialog" }},
			properties = { titlebars_enabled = true }
		},
		{
			rule = { class = "Firefox" },
			properties = { tag = "Tag4" }
		}
	}
```

**Comment by LukaK** [comment]
Thank You for the snippets.
I have added code from the reference and it works great.
