### ISSUE TITLE
Swapping screens causes awesome to reload

### ISSUE THREAD

**Issue by ionsquare** [worron/awesome-config#22]
I have 3 monitors and about 50% of the time they are loaded in the wrong order. To fix this I've attempted to add a hotkey to [swap screen positions](https://awesomewm.org/doc/api/classes/screen.html#screen:swap) in the colorless config.

I've added the following block to the `Global keys` section in  `keys-config.lua`:

```lua
{
  { env.mod }, "o", function () screen[1]:swap(screen[3]) end,
  { description = "Swap screen position", group = "Screen navigation" }
},
{
  { env.mod, "Control" }, "Right", function () awful.screen.focus_relative(1) end,
  { description = "View next screen", group = "Screen navigation" }
},
{
  { env.mod, "Control" }, "Left", function () awful.screen.focus_relative(-1) end,
  { description = "View previous screen", group = "Screen navigation" }
},
```

For some reason though, using the swap hotkey causes awesome to reload (as if `mod+ctrl+r` was pressed). The next/previous screen hotkeys work fine.

I've tried adding a debug message to show `screen[1].index` and `screen[3].index` and it shows the correct index so the `screen` variable is available. I've also tried assigning a different key combination but get the same problem.

I have this same hotkey in my old awesome-copycats config and it works there without any issue.

Any idea what might be causing this to reload awesome when using redflat instead of swapping the screens like it should?

**Comment by worron** [comment]
Unfortunately it's by design. In `signals-config.lua` the root can be found
```lua
	-- Awesome v4.0 introduce screen handling without restart.
	-- Since I'm using single monitor setup and I'm too lazy to rework my panel widgets for this new feature,
	-- simple adding signal to restart wm on new monitor pluging.
	-- For reference, screen-dependent widgets are
	-- redflat.widget.layoutbox, redflat.widget.taglist, redflat.widget.tasklist
	screen.connect_signal("list", awesome.restart)
```

I've been using single monitor setup all the time so I have neither the wish nor the capacity to polish multi monitor behavior. You can disable restart on screen `list` (or just replace it with pair `added` `removed`) signal and check how it goes, but I can't guaranty correct work for mentioned widgets this way. Hope for your understanding.

**Comment by ionsquare** [comment]
Yes absolutely, that is extremely helpful, thanks!

I will play around with it and see if I can find an elegant way to make it work without breaking anything, and if I can, I'll submit a PR for you to review and you can decide whether or not it's worth merging.

**Comment by ionsquare** [comment]
Commenting that line out does fix the issue, I can't tell what breaks without it though. No sense in leaving this issue open anyway.
