### ISSUE TITLE
 в Fedora 28 не работает смена клавиатуры

### ISSUE THREAD

**Issue by vansanblch** [worron/awesome-config#23]
Скролл над виджетом клавиатуры, как я понял, должне менять раскладку, но этого не происходит.

Вводил в консоле `dbus-send --dest=ru.gentoo.KbddService /ru/gentoo/KbddService ru.gentoo.kbdd.next_layout` - тоже ничего не происходит. Помогает только `setxkbmap`.

Можно это как-то пофиксить или указать свобственные клавиши для смены раскладки?

**Comment by worron** [comment]
Данный виджет работает только с демоном [kbdd](https://github.com/qnikst/kbdd).

**Comment by vansanblch** [comment]
Понял. Спасибо.

**Comment by vansanblch** [comment]
Разобрался как настроить. Но я правильно понял что смена раскладки осуществляется только скроллом над виджетом? Планируете ли вы добавить переключение раскладки через комбинацию клавиш?

**Comment by worron** [comment]
Нет, не планирую, у меня комбинация задана через `setxkbmap` на старте системы
```
setxkbmap -layout 'us,ru' -option grp:rctrl_rshift_toggle
```

Но ничего не мешает добавить в свои настройки хоткеев (`keys-config.lua`) одну из команд
```lua
function() redflat.widget.keyboard:toggle() end)     -- следуюшая раскладка
function() redflat.widget.keyboard:toggle(true) end) -- предыдущая раскладка
```

**Comment by vansanblch** [comment]
Супер.
