### ISSUE TITLE
Help with app menu

### ISSUE THREAD

**Issue by ema79** [worron/awesome-config#25]
Hi Worron tnx again for your awesome themes. Still love them ;) And still playin trying to work on them.

I can't figure how to edit the appmenu. Do I have to edit xdg menu? Or do I have to take a look at distro menu as suggested on Arch wiki?

P.S. What about adding a weather widget? I added one in my config, maybe one day I'll be alble to use ad it in redflat.

Bye

**Comment by worron** [comment]
Hi. Main menu initialized in `menu-config.lua` file for selected color. Application submenu generated automatically by `redflat` scripts from desktop files, [here is](https://github.com/worron/awesome-config/issues/24#issuecomment-436981434) explained how to set some parameters for generating. Menu widget appearance can also be changed in theme file, see "Menu config" section.

Weather widget is quite possible but not in the nearby future. Right now I'm working on major update for `redflat` and configs (in very slow pace thought, another month or two for sure) so no significant changes until then planned.

**Comment by worron** [comment]
Ok, big update released. I was planning to think about weather widget for awesome wm next, but found that already exists [some](https://github.com/streetturtle/awesome-wm-widgets/tree/master/weather-widget), no sense to reinvent wheel .
