### ISSUE TITLE
tray icons theme

### ISSUE THREAD

**Issue by mchoji** [worron/awesome-config#28]
I'm using ruby shade theme and I managed to adapt everything to my system except the tray icons.
I am using ACYLS icon theme but the icons are still in their "default" style. I don't know if I am missing something
![tray](https://user-images.githubusercontent.com/7395296/58383002-b7b6fe80-7fa7-11e9-8985-a26b5c7d66ef.png)

How can I make those icons looks like those from the video?
![redflat-tray](https://user-images.githubusercontent.com/7395296/58383033-1d0aef80-7fa8-11e9-889b-0b27934bae9d.png)

**Comment by worron** [comment]
ACYLS  theme should be used by application itself. For example gtk3 application theme can be configured with `~/.config/gtk-3.0/settings.ini`. Also not all apps support tray icon customization.

**Comment by mchoji** [comment]
Thank you! Indeed, there are compatibility problems with some of my apps.
