### ISSUE TITLE
Network widget does not scale with speed

### ISSUE THREAD

**Issue by pescio** [worron/awesome-config#29]
The blue-theme network widget in the wibar does not scale when the download/upload speed changes.
It just sits at one blue dash colored. If the speed is high the two white columns become red, which is good.
Where should I look at to fix my problem?

**Comment by worron** [comment]
Not sure if I get it right, but do you edit [this setting](https://github.com/worron/awesome-config/blob/30333b85ebc3b845429afd426e536eb669bb2363/color/blue/rc-blue.lua#L184) according your network bandwidth?

**Comment by pescio** [comment]
I did, but nothing changes. The desktop widget works like a charm, but the wibar doesn't. I'm playing with [widg:set_value](https://github.com/worron/redflat/blob/05d83ee2c2724eab88fde7a7656f872a14d98829/widget/net.lua#L81)  but the colored dash is only one. If I put 0 there, then no dash is colored. It seems some issue with the painting of the dashes.

**Comment by pescio** [comment]
Btw, the cpu widget has the same problem. It doesn't go above 1 colored dash. I'm missing the point where the rendering is performed.

**Comment by pescio** [comment]
Ok maybe I found it. If I force a "4" value [here](https://github.com/worron/redflat/blob/05d83ee2c2724eab88fde7a7656f872a14d98829/gauge/monitor/double.lua#L50) then it shows 4 dashes colored.
I suppose there's some problem with passed values or math, but I cannot debug it or see the values. Any idea how to do this? Thanks.

**Comment by worron** [comment]
I screw up during last refactoring in this widget. Thank you for pointing. Should be fixed with worron/redflat@2fb6eb3.

**Comment by pescio** [comment]
Yeah! I confirm it's fixed, thanks
