### ISSUE TITLE
Awesome 4.0

### ISSUE THREAD

**Issue by kenanpelit** [worron/awesome-config#3]
Great work, I use it with pleasure. Do you think of opening a new branch for Awesome 4.0?

**Comment by worron** [comment]
Yes, I have this kind of plan. But 4.0 was really massive update, It has a lot of new cool features and ideas, so current config needs a serious rework. I think it's safe to say that repo updates will be no earlier than a few months.

**Comment by worron** [comment]
Somehow I finished porting this scripts to Awesome 4.0. Now `master` branch is for v4.0+ and `v356` branch for v3.5.6.

Some improvements:
* New minimalistic `rc-colorless` config, should work without editing on any random system. Can be used as base for building your own setup.
* Unified hotkeys system. Now hotkeys for widgets and layouts can be defined with the same format as global keys. And advanced hotkeys helper will show all currently active keys.
* Minor fixes and refactoring here and there. Some widget may have slightly different behavior. Several new and updated icons.

Regressions:
* Temporary remove exaile player widget. It needs a really serious rework, may be do it in future.
* Titlebar tabs feature was dropped. To be honest I don't like it from the start: code was pretty messed and hard to maintain. Furthermore, the day when [#644](https://github.com/awesomeWM/awesome/pull/644) will be merged make all my effort useless. So this feature is removed by now.

Of course It needs some testing and polishing now. Feel free to open separate issue if you meet any problem with updated configs.
