### ISSUE TITLE
Volume widget works only after awesome restart

### ISSUE THREAD

**Issue by pescio** [worron/awesome-config#30]
The volume widget - with the colored bars - works only after restart.
I'm using the blue theme and I've just configured some minor things.

Steps to reproduce:

1. log in 
2. raise volume with keyboard controls
3. the volume is not raised
4. press ctrl+mod4+r (restart awesome)
5. volume controls work magically

**Comment by worron** [comment]
I'll try to investigate this. Pulse widget definitely in bad shape right now and needs some fixes.

**Comment by pescio** [comment]
I'll be glad to help if I know how to debug it.

**Comment by worron** [comment]
I added some changes to make pulse widgets individually configurable. It may be not related with current issue, but should be done first anyway.

Now pulse sink can be set manually per widget, somethings like
```lua
volume.widget = redflat.widget.pulse(
	{ sink = "alsa_output.pci-0000_00_1f.3.analog-stereo" },
	{ widget = redflat.gauge.audio.blue.new }
)
```

Can you test if this workaround  help in your case? You have to update `redflat` submodule and change your blue config according [this](https://github.com/worron/awesome-config/commit/9454e7b42f54d00c145bce100eb47b84000ca494#diff-bc8c241b0855402deffba60adcd5d4d3) and [this](https://github.com/worron/awesome-config/commit/9454e7b42f54d00c145bce100eb47b84000ca494#diff-aa120a87aecff29be701807639e4a86b).

**Comment by pescio** [comment]
yeah, that worked!
I configured the sink like this, according to my hardware

volume.widget = redflat.widget.pulse({ sink = "alsa_output.pci-0000_00_1f.3.iec958-stereo" }, { widget = redflat.gauge.audio.blue.new })
