### ISSUE TITLE
Ruby Wallpaper

### ISSUE THREAD

**Issue by hristijankiko** [worron/awesome-config#33]
Hi,

I am trying to set up the Ruby theme but I cannot find the wallpaper. I did check the other wallpaper related issues created but it seems like the wallpapers for Ruby and Steel are not included in the answer.

Is there any chance I can get those?

Thanks.

**Comment by worron** [comment]
Sure. [Here](https://github.com/worron/wallpapers/blob/master/traced/ruby_rose_rwby_minimal_by_max028.svg) and [here](https://github.com/worron/wallpapers/blob/master/traced/psycho_pass_by_welterz.svg) are vector source. And [here](https://yadi.sk/d/3tm4964X0bPTNw) is render which was used for screenshots.

**Comment by hristijankiko** [comment]
Thanks
