### ISSUE TITLE
Hotkey helper doesn't fit in the screen

### ISSUE THREAD

**Issue by Ornanovitch** [worron/awesome-config#35]
Hello @worron 

First of all, thank you very much for sharing your work, it's such a beautiful customization :)
I almost finished to adapt the blue theme for my computer, and I have a little display problem with the Hotkey (Mod4+F1). Look at how it is displayed : 

![2019-07-23-104326_1600x900_scrot](https://user-images.githubusercontent.com/34077099/61697199-11813e00-ad37-11e9-8c17-dee1d99c4824.png)

I searched everywhere in the configs files, I don't know how to fix this.

Could you help me ?

Thanks again,

**Comment by worron** [comment]
You can decrease size numbers [here](https://github.com/worron/awesome-config/blob/35cfc533445e50627b61c659825215d6fc564e1a/themes/colored/theme.lua#L196-L197). For better understanding check [full style](https://github.com/worron/awesome-config/blob/35cfc533445e50627b61c659825215d6fc564e1a/themes/colorless/theme.lua#L962-L982) for helper widget. Also I recommend set mono-space font for [widget lines](https://github.com/worron/awesome-config/blob/35cfc533445e50627b61c659825215d6fc564e1a/themes/colored/theme.lua#L36).

**Comment by Ornanovitch** [comment]
Thank you ! I try to fix this today :)

**Comment by Ornanovitch** [comment]
Worked like a charm, thx again !
