### ISSUE TITLE
How to bring default tasklist back?

### ISSUE THREAD

**Issue by sooqua** [worron/awesome-config#36]
I replace
```Lua
tasklist[s] = redflat.widget.tasklist({ screen = s, buttons = tasklist.buttons }, tasklist.style)
```
with 
```Lua
    tasklist[s] = awful.widget.tasklist {
        screen  = s,
        filter  = awful.widget.tasklist.filter.currenttags,
        buttons = tasklist_buttons
    }
```
And it brings old tasklist back with icons and title, but "tasks" are centered and if i create more than 4 tasks the widget just disappears, even if I close all but one window it won't show up anymore.

**Comment by worron** [comment]
>but "tasks" are centered

To restore default behavior replace whole section below with `tasklist[s],`
```lua
			{ -- middle widget
				layout = wibox.layout.align.horizontal,
				expand = "outside",

				nil,
				env.wrapper(tasklist[s], "tasklist"),
			},
``` 
>and if i create more than 4 tasks the widget just disappears

Can't reproduce this. Report If problem still appear after previous step done, I'll try to investigate then.

**Comment by sooqua** [comment]
Oh my god it's fixed! Thank you so much!!
Awesome configuration btw. Great, great job.
