### ISSUE TITLE
How to isolate only one tag properties

### ISSUE THREAD

**Issue by Ornanovitch** [worron/awesome-config#38]
Hi @worron !
Thanks again for your config, very cool to use

I have 6 tags, and I use the blue theme with the orange style for taglist : 
`taglist.style = { separator = separator, widget = redflat.gauge.tag.orange.new, show_tip = true }`

I want that style to work with tag 2 to 6, but not for the first. For this one, I'd like to use a specific icon. I followed [the documentation](https://awesomewm.org/doc/api/classes/tag.html), and wrote this line for my specific tag in the rc-blue : 
```
        awful.tag.add("Mail", {
            icon   = "/home/ornanovitch/.ornanocfg/mail.svg",
        })
```
The tag does appears, but the icon config doesn't work, it seems that redlat.gauge.tag.orange overrides this specific properties.

How could I achieve this little hack ?

Regards,

**Comment by worron** [comment]
Not trivial task actually,  `redlat.gauge.tag.orange` is custom widget for changing tag appearance and it doesn't support icons. To achieve described behavior whole widget should be redesigned.

But there are some workarounds. You can have two different taglist, first of them will display iconic tags, the second iconless. Here is quick and dirty changes to add default `awful` taglist to blue config
```lua
		-- tags
		awful.tag.add("Test", { icon = beautiful.icon.awesome, })
		awful.tag({ "Main", "Full", "Edit", "Read", "Free" }, s, { al[5], al[6], al[6], al[4], al[3] })

		-- layoutbox widget
		layoutbox[s] = redflat.widget.layoutbox({ screen = s })

		-- taglist widget
		local default_taglist = awful.widget.taglist {
			screen  = s,
			filter  = function (t) return t.icon end,
			buttons = taglist.buttons
		}
		taglist[s] = redflat.widget.taglist(
			{ screen = s, buttons = taglist.buttons, hint = env.tagtip, filter  = function (t) return not t.icon end },
			taglist.style
		)

		-- tasklist widget
		tasklist[s] = redflat.widget.tasklist({ screen = s, buttons = tasklist.buttons }, tasklist.style)

		-- panel wibox
		s.panel = awful.wibar({ position = "bottom", screen = s, height = beautiful.panel_height or 36 })

		-- add widgets to the wibox
		s.panel:setup {
			layout = wibox.layout.align.horizontal,
			{ -- left widgets
				layout = wibox.layout.fixed.horizontal,

				env.wrapper(layoutbox[s], "layoutbox", layoutbox.buttons),
				separator,
				default_taglist,
				env.wrapper(taglist[s], "taglist"),
				separator,
			},
```

**Comment by f00wl** [comment]
Hi there,

Firstly, thanks you @worron for this крута awesome config!

According to [this post](https://stackoverflow.com/questions/21152068/load-svg-with-cairo) and the [official documentation]() cairo doesn't support svg import, you probably should use something else to convert svg to cairo ([Librsvg](https://en.wikipedia.org/wiki/Librsvg)).
However I just submit a request to @worron [redflat project](https://github.com/worron/redflat) to add [support for text inside orange tags](https://github.com/worron/redflat/pull/50).

Then just use a font that support glyph icons, like [NerdFont](https://nerdfonts.com), and adapt your theme to use it:

`theme.lua`
```lua
    -- Tag (base element of taglist)                                                            
    ------------------------------------------------------------                                
    self.gauge.tag.orange = {                                                                   
        width        = self.gauge.monitor.circle.width,      -- widget width
        line_width   = self.gauge.monitor.circle.line_width, -- width of arcs
        iradius      = self.gauge.monitor.circle.iradius,    -- radius for center point
        radius       = self.gauge.monitor.circle.radius,     -- arcs radius
        cgap         = 0.314,                                -- gap between arcs in radians
        min_sections = 1,                                    -- minimal amount of arcs
        show_min     = false,                                -- indicate minimized apps by color
        text         = true,                                 -- replace middle circle by text
        font         = self.cairo_fonts.tag,                 -- font for text
        color        = self.color                            -- colors (main used)
    }
```

`rc-theme.lua`
```lua
-- tags
awful.tag({ "", "", "", "", "", "", "", "", "" }, s, awful.layout.layouts[1])
```

it's looks like this:

![](https://i.imgur.com/JRkXGhW.png)

**Comment by worron** [comment]
>but this type of tag configuration produces two different problems

Yeah, at least screen property was missed in my code example
```lua
awful.tag.add("Test", { icon = beautiful.icon.awesome, screen = s })
```
As you found already I'm not good at multi screen configuration, you'd better to go further on your own using [api references](https://awesomewm.org/apidoc/core_components/tag.html).

**Comment by Ornanovitch** [comment]
Thanks again to both of you, I just resolved my problems !
So now thanks to @f00wl I have font awesome icons on my taglist, and after having searching for a while how to setup different taglist for each screen, it finally works !

Here is the beginning of my screen section setup : 
```
-- aliases for setup
local al = awful.layout.layouts

-- setup

my_tags = {
    tags = {
        { names =  { "", "", "", "", "", "", "" },
          layout = { al[3], al[3], al[3], al[3], al[3], al[3], al[3] },
        },
        { names =  { "", "", "", "", "" },
          layout = { al[3], al[3], al[3], al[3], al[3] },
        },
    }
}

awful.screen.connect_for_each_screen(
  function(s)
    env.wallpaper(s)
    -- wallpaper
    screen_index = s.index

    awful.tag(my_tags.tags[screen_index].names, s, my_tags.tags[screen_index].layout)
``` 

My next challenge will be to setup a conditional configuration : 
- If only 1 screen is connected, `my_tags1 = {` is applied
- if 2 screens are connected, `my_tags2 = {` is applied

I take any suggestion :smiley_cat: 

Until there, my initial problem is solved
