### ISSUE TITLE
Recreate the compact Titlebar config

### ISSUE THREAD

**Issue by pished** [worron/awesome-config#39]
First off, you got a really sweet config and has got me into giving awesome a try from i3. I only started learning LUA 3 days ago and pretty much the awesome API just as long.

I'm trying to recreate your compact titlebar (only bars to signal window settings) and read your answer to another [issue](https://github.com/worron/awesome-config/issues/4#issuecomment-295304210) which helped give me a better understanding. 

I know the settings are in the `titlebar-config.lua`, but I am trying to figure out the minimum I need to code in to get that effect myself. As far as I can tell pretty much everything is "inheriting" from `redflat (not sure what it does)` > `colorless/titlebar-config.lua` > `shade/ruby/titlebar-config.lua`

I _think_ that to get a little margin around the titlebar, you wrap it in a wibox widget container since there is no gap by default

`shade/ruby/titlebar-config.lua` (no real reason I picked ruby)
```lua
			-- build mini titlebar model
			local base  = wibox.widget({
				nil,
				{
					right  = style.mark_mini.gap,
					redtitle.mark.focus(c, style.mark_mini),
					layout = wibox.container.margin,
				},
				{
					redtitle.mark.property(c, "floating", style.mark_mini),
					redtitle.mark.property(c, "sticky", style.mark_mini),
					redtitle.mark.property(c, "ontop", style.mark_mini),
					spacing = style.mark_mini.gap,
					layout  = wibox.layout.fixed.horizontal()
				},
				buttons = all_buttons,
				layout  = wibox.layout.align.horizontal,
			})
```

I think this is the responsible code but I am trying to do it without redflat, if that's possible.

**Comment by worron** [comment]
`redflat` is my extension module for awesome wm and files in this repo actually is bunch of settings for it. Actual code mostly located in the [module](https://github.com/worron/redflat).  So if you want to build your own config without using `redflat` this files not very helpful, better to go with [official docs](https://awesomewm.org/apidoc/popups_and_bars/awful.titlebar.html).

It's very possible to recreate compact title bar with default config, but it will require some extra code. If you are still interested, I'll provide example when I get a bit time.

**Comment by pished** [comment]
```lua
client.connect_signal("request::titlebars", function(c)
    local top_titlebar = awful.titlebar(c, {size = dpi(8)})
    -- buttons for the titlebar
    local buttons = gears.table.join(awful.button({}, 1, function()
        c:emit_signal("request::activate", "titlebar", {raise = true})
        awful.mouse.client.move(c)
    end), awful.button({}, 3, function()
        c:emit_signal("request::activate", "titlebar", {raise = true})
        awful.mouse.client.resize(c)
    end))
    top_titlebar:setup{
        {
        { -- Left
            awful.titlebar.widget.iconwidget(c),
            buttons = buttons,
            layout = wibox.layout.fixed.horizontal
        },
        { -- Middle
            { -- Title
                align = "center",
                widget = awful.titlebar.widget.titlewidget(c)
            },
            buttons = buttons,
            layout = wibox.layout.flex.horizontal
        },
        layout = wibox.layout.align.horizontal
    },
    bottom = beautiful.border_width,
    color = beautiful.color.border,
    layout = wibox.container.margin,
    }
end)
```

I've managed to hack it a bit. It's kinda strange because margin cut _into_ the titlebar instead of giving it a buffer. I just gotta figure out how you managed the other 3 marks -- it looks like signals trigger their color change? I'm gonna have to look more into those because I don't get 'em much

**Comment by worron** [comment]
One of possible approaches
```lua
-- simple helper to select active or inactive color
local function color_chooser(is_highlight)
    return is_highlight and '#A02020' or '#2020A0'
end

client.connect_signal("request::titlebars", function(c)
    -- make title bar with fixed height and colors to disable background changing
    local top_titlebar = awful.titlebar(c, { size = 16, bg_normal = '#202020', bg_focus = '#202020' })

    -- there are ton variants to make your own mark widget
    -- and here is quick and dirty: colored background widget with empty image widget
    local empty_widget = wibox.widget.imagebox()
    empty_widget:set_forced_width(32)

    local focus_mark = wibox.container.background(empty_widget)
    c:connect_signal("focus", function(_) focus_mark:set_bg(color_chooser(true)) end)
    c:connect_signal("unfocus", function(_) focus_mark:set_bg(color_chooser(false)) end)

    local ontop_mark = wibox.container.background(empty_widget)
    c:connect_signal("property::ontop", function(_) ontop_mark:set_bg(color_chooser(c.ontop)) end)
    ontop_mark:set_bg(color_chooser(c.ontop))

    local maximize_mark = wibox.container.background(empty_widget)
    c:connect_signal("property::maximized", function(_) maximize_mark:set_bg(color_chooser(c.maximized)) end)
    maximize_mark:set_bg(color_chooser(c.maximized))

    top_titlebar:setup {
        {
            nil, -- left part is empty
            {
                -- middle
                focus_mark,
                right = 8,
                layout = wibox.container.margin,
            },
            {
                -- right
                ontop_mark,
                maximize_mark,
                spacing = 8,
                layout  = wibox.layout.fixed.horizontal()
            },
            layout = wibox.layout.align.horizontal
        },
        bottom = 4, top = 4, right = 8, left = 8,
        layout = wibox.container.margin,
    }
end)

```

**Comment by pished** [comment]
I'm getting a better sense of how these configs are done now. That's clever to wrap and imagebox with a background container to be able to hotswap the color. I gotta take a 3rd look at the signal doc's -- still don't quite get how they work.

I wish github had a PM system, I didn't want to open an issue for this because it wasn't really an "issue" with the code. Thanks for the snippet!
