### ISSUE TITLE
Top panel

### ISSUE THREAD

**Issue by VPeruS** [worron/awesome-config#4]
What is the purpose of the upper panel? There seems to be close button or something like that. But i have only little rectangels.  Also if window is small you cannot see if it focused or not.
![bar](https://cloud.githubusercontent.com/assets/7927055/25183605/ba2eb466-2520-11e7-9a15-d06a329e18f0.png)

**Comment by worron** [comment]
Seems like saying "top panel" you are meaning titlebar.

Titlebar appearance defined with `titlebar-config.lua` config. It can be built as a regular awesomewm widget, and you can set there anything you want, like buttons, text, images. I personaly prefer use hotkeys for window managment, thats why my titlebar has no buttons by default. These little rectangles are simple indicators and they show window state (focus, floating, sticky, etc) by color. So just edit `titlebar-config.lua` according to your thinks.

Furthermore, you can build several titlebar models (see `light titlebar model` and `full titlebar model` code) and switch them by hotkeys, `Mod4+Control+t` by default.

Also focus indicator sure visible except if window width less than 150px. Sorry, I just never met such small windows in my workflow.

**Comment by VPeruS** [comment]
Thanks for answer.
