### ISSUE TITLE
Question about qlaunch

### ISSUE THREAD

**Issue by mchoji** [worron/awesome-config#42]
For some reason I can't have proper icon for sublime text on quick launch. I have tried every sort of tweak like changing *.desktop file names and configs, icon names etc. without success (slot 9 in the figure).
I have read the code on redflat dir but I'm surely missing something...
Some notes about my system:
 * sublime_text.desktop file is at /usr/share/applications
 * Icon=sublime-text entry in that file
 * scalable/apps directory inside icon theme directory
 * sublime-text.svg at the proper location

Any idea on how to get it to work?
![qlaunch](https://user-images.githubusercontent.com/7395296/74679631-2a52b480-519d-11ea-8d76-40785754bbe9.png)

**Comment by worron** [comment]
`Qlaunch` a bit dirty widget full of workarounds. It works assuming that application class appear the same as launch command which not always true. [Here](https://github.com/worron/awesome-config/blob/380f5b80798ff539d64563fa365ac1356326205d/themes/colorless/theme.lua#L934-L939) in config you can see an extra directory added and there I put specially prepared desktop files to trick the widget. Something like this
```
[Desktop Entry]
Name=Pycharm
Comment=Fake launcher
Exec=jetbrains-pycharm-ce
Icon=pycharm

```
Exec option should be changed to sublime app exact class (can be quickly found in taskbar right click menu) and Icon option to what you want.

**Comment by mchoji** [comment]
Thanks! That did the trick, but only after I make a change to `dfparser` to allow underscore in the regex related to `Exec` option.
I have sent a PR in case you think it is plausible.
![qlauncher-fix](https://user-images.githubusercontent.com/7395296/74706733-85fd5c00-51f6-11ea-939f-da3de16c3611.png)
