### ISSUE TITLE
Many questions

### ISSUE THREAD

**Issue by Kefedric** [worron/awesome-config#43]
Hi,

1st : **Thanks for your work !**
I’am using your color/blue theme and I try to make everything work and customize it.
I’am on Arch with awesome 4.3.1

2nds Questions :

1) What is your mouse cursor in the video demo ?

2) update widget, what is the intended behavior ? (what I see is a `pacman -Qu` witch return nothing if no other command are done before, like a `pacman Sy` witch isn’t recommanded practice)

3) How can I enable the Mouseover tooltip on desktop widget like showned in your demo video (I searched into the ruby config file but in vain)

4) HDD temperature desktop widget using smartctl you said "Should be configured to run from user."
but I search on internet It says everywhere it needed root acces, how to make it work ?

5) About the GPU temperature I used the system.thermal.nvsmi fonction (but it didn’t show the value) so I had to change the line 137 from color/blue/desktop-config.lua to :
`{ meter_function = system.thermal.nvsmi, maxm = 105, crit = 80, name = "gpu" }`
Could you explain why ? (I don’t really get the diffrence between the meter and async function)

6) I was unable to make the lmsensors widget work (fan & cpu temp)
If I get it right color/blue/desktop-config.lua call for redflat/system.lua witch look the result of the `sensors`
Here the result of my `sensors` command, see if something is wrong

```
coretemp-isa-0000
Adapter: ISA adapter
cpu:          +24.0°C  (high = +80.0°C, crit = +100.0°C)
Core 0:       +18.0°C  (high = +80.0°C, crit = +100.0°C)
Core 1:       +19.0°C  (high = +80.0°C, crit = +100.0°C)
Core 2:       +16.0°C  (high = +80.0°C, crit = +100.0°C)
Core 3:       +19.0°C  (high = +80.0°C, crit = +100.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +27.8°C  (crit = +119.0°C)
temp2:        +29.8°C  (crit = +119.0°C)

nct6793-isa-0a20
Adapter: ISA adapter
in0:                   728.00 mV (min =  +0.00 V, max =  +1.74 V)
in1:                     1.01 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in2:                     3.41 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in3:                     3.36 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in4:                     1.02 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in5:                   144.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in6:                   952.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in7:                     3.41 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in8:                     3.06 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in9:                     1.01 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in10:                    1.11 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in11:                    0.00 V  (min =  +0.00 V, max =  +0.00 V)
in12:                    1.02 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in13:                  600.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in14:                    1.54 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
fan1:                     0 RPM  (min =    0 RPM)
fan2:                   311 RPM  (min =    0 RPM)
fan3:                   465 RPM  (min =    0 RPM)
fan4:                     0 RPM  (min =    0 RPM)
fan5:                     0 RPM  (min =    0 RPM)
SYSTIN:                 +30.0°C  (high =  +0.0°C, hyst =  +0.0°C)  ALARM  sensor = CPU diode
CPUTIN:                +127.5°C  (high = +80.0°C, hyst = +75.0°C)  ALARM  sensor = CPU diode
AUXTIN0:                +28.5°C    sensor = thermistor
AUXTIN1:                +20.0°C    sensor = thermistor
AUXTIN2:               -128.0°C    sensor = thermistor
AUXTIN3:                 -2.0°C    sensor = thermistor
PECI Agent 0:           +23.0°C  
PCH_CHIP_CPU_MAX_TEMP:   +0.0°C  
PCH_CHIP_TEMP:           +0.0°C  
PCH_CPU_TEMP:            +0.0°C  
intrusion0:            ALARM
intrusion1:            ALARM
beep_enable:           disabled

pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +36.5°C 
```

I hope you have some time to answer these question (wich are mairly due to my lack of programing skills I think)

**Comment by Kefedric** [comment]
About 6) I found the issue : was on color/blue/desktop-config.lua line 121
`		cpu       = { match = "CPU:%s+%+(%d+)%.%d°[CF]" },`
I replace with
`		cpu       = { match = "cpu:%s+%+(%d+)%.%d°[CF]" },`

don’t know if my `sensors` output is standar or not, maybe worth changing file ?

**Comment by worron** [comment]
>What is your mouse cursor in the video demo ?

X-Steel-GRAY-negative.

>update widget, what is the intended behavior ? (what I see is a pacman -Qu witch return nothing if no other command are done before, like a pacman Sy witch isn’t recommanded practice

That's exactly how it works, `pacman Sy` scheduled by cron outside the config. Can't see how it's bad, may be I'm missing something. This config full of hacky recipes anyway so choose on your own to follow it or not. 

>HDD temperature desktop widget using smartctl you said "Should be configured to run from user."
but I search on internet It says everywhere it needed root acces, how to make it work ?

And this one is actually bad practice, such utility is not intended to run from user. I just want my thermal monitors so badly that it just done. I leave recipe here but keep in mind it's very dirty solution.
```bash
sudo chmod o-x /usr/sbin/smartctl
sudo chown :your_user_name /usr/sbin/smartctl
sudo chmod u+s /usr/sbin/smartctl
```

>I don’t really get the diffrence between the meter and async function

`meter_function` is for old outdated functions. It works in synchronous way so may cause WM freeze in worst case scenario. `async` is for modern meter functions, which asynchronous and callback based. It better to be all meter function asynchronous but many parts of this confing pretty old and that's how it is. Which function where only by `redflat.system` source code can be defined.

>The expression for my cpu fan should be : "fan2:%s+(%d+)%sRPM" but it don’t work any idear ?

The pattern seems right, so have no clue, sorry.

**Comment by Kefedric** [comment]
Thanks for your aswers.

About the update it was in the ArchWiki system maintenance page they told :

> Avoid certain pacman commands
Avoid doing partial upgrades. In other words, never run pacman -Sy; instead, always use pacman -Syu.

Anyway, thanks to your work my awesomeWM is so beautifull now !

**Comment by paulbdavis** [comment]
@Kefedric There is a `pacman-contrib` package that contains a script `checkupdates` for this purpose, it allows you to sync the repos as a user and see if your system needs any updates

**Comment by Kefedric** [comment]
Thank you @paulbdavis `checkupdates` works well indeed ;)

**Comment by Kefedric** [comment]
I came back at the fan issue.
Could you show me the output of your `sensors` command ?
(for me to try understand where’s the issue on my side)
