### ISSUE TITLE
ff-sync

### ISSUE THREAD

**Issue by rakanalh** [worron/awesome-config#44]
Hello,

I noticed that you have:

https://github.com/worron/awesome-config/blob/380f5b80798ff539d64563fa365ac1356326205d/color/blue/autostart-config.lua#L24

Do you mind sharing this file? couldn't find it anywhere on the internet and i can use it to sync firefox tabs into qutebrowser.

Thanks

**Comment by worron** [comment]
Sorry, I'm afraid it's not what you are looking for. It's some script to sync firefox profiles in very specific way which will be useless outside of my home environment.

**Comment by rakanalh** [comment]
fair enough. thanks for the answer :)
