### ISSUE TITLE
Blue theme - focus_switch_byd not working

### ISSUE THREAD

**Issue by rakanalh** [worron/awesome-config#45]
Hello,

Using the blue theme, i tried the following:
1. Launch Firefox on workspace 1
2. Launch qutebrowser on workspace 1 (3 windows)

The task list correctly shows 2 items (qutebrowser + firefox).

However, pressing `Mod4 + (i, j, k, l)` doesn't seem to work switching focus to the different qutebrowser windows and firefox. Tried chaing the code to:
```
		{
			{ env.mod }, "l", awful.client.focus.byidx(-1),
			{ description = "Go to right client", group = "Client focus" }
		},
		{
			{ env.mod }, "j", awful.client.focus.byidx(1),
			{ description = "Go to left client", group = "Client focus" }
		},
```

But that isn't working either. Not sure what the problem is here really.

**Comment by worron** [comment]
Never experienced such problem. Both `awful.client.focus.bydirection` `awful.client.focus.byidx` are functions from standard WM lib so has nothing to do with config. Try to reproduce this with default awesomewm config, possible it's upstream issue.

**Comment by rakanalh** [comment]
I believe this was because i was using the "maximized" layout which somehow prevents moving between clients. On a normal tiling layout the shortcuts work without issues.
