### ISSUE TITLE
tasklist - display actual title instead of application name

### ISSUE THREAD

**Issue by rakanalh** [worron/awesome-config#46]
Does redflat's tasklist widget have an option to display the window title instead of the application name? example for that would be say, firefox where the title of the window is the title of the page that firefox currently displays. Or should i consider this option: https://github.com/worron/awesome-config/issues/36?

**Comment by worron** [comment]
No, `redflat` task list was not designed for such option. It has fixed widget width for limited number of symbols. But you can try some experiments on your own starting with this
```patch
diff --git a/widget/tasklist.lua b/widget/tasklist.lua
index db17adc..5b63f31 100644
--- a/widget/tasklist.lua
+++ b/widget/tasklist.lua
@@ -128,7 +128,7 @@ local function get_state(c_group, style)
 	end
 
 	local class = c_group[1].class or "Undefined"
-	state.text = names[class] or string.upper(string.sub(class, 1, chars))
+	state.text = c_group[1].name
 	state.num = #c_group
 	state.icon = style.custom_icon and style.icons[style.iconnames[class] or string.lower(class)]
 

```

And turn back to default awesomewm tasklist is an option of course.

**Comment by rakanalh** [comment]
Thanks, i guess with grouping it makes sense to display the app name instead.
