### ISSUE TITLE
minitray shows no icons

### ISSUE THREAD

**Issue by rakanalh** [worron/awesome-config#47]
Hello,

Using the blue theme, hovering on the minitray, it says "3 apps". However, when clicking on it i get a box with a background and no icons. Is this an issue in redflat or can this be fixed somehow inside the theme?

**Comment by worron** [comment]
Very strange. Which awesomewm version do you use?  What are these applications? Does tray works right on default wm config?

**Comment by rakanalh** [comment]
The applications are telegram / nm-applet and discord. I tried the default wm config and the icons are appearing without issues.

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**Comment by worron** [comment]
Have no clue then, unfortunately. Basically `minitray` its standard awesomewm tray on floating wibox. I have no issues with discord and nm-applet tray icons. You can try other themes or adjust wibox size [here](https://github.com/worron/awesome-config/blob/master/themes/colorless/theme.lua#L531) just in case. Or just use standard tray as last option.

**Comment by rakanalh** [comment]
My bad. Apparently, i had 3 monitors connected and only one of them can display the systray (a limitation in the systray implementation i guess). 

Thanks for the help @worron
