### ISSUE TITLE
Something got wrong in 'find' function

### ISSUE THREAD

**Issue by ChunjieShan** [worron/awesome-config#49]
Hi there!
I've just installed your configuration files, and I got this bug info:
~/.config/awesome/redflat/service/dfparser.lua:378: bad argument #1 to 'find' (string expected, got nil)
I'll be very glad if you are able to tell me how to fix it.

**Comment by worron** [comment]
It seems like one of your desktop file have some unexpected launch command. Here is patch which can possibly exclude such files from `dfparser` icon handler. Please report if it works.

```diff
diff --git a/service/dfparser.lua b/service/dfparser.lua
index 13c9ad4..46be59d 100644
--- a/service/dfparser.lua
+++ b/service/dfparser.lua
@@ -375,8 +375,10 @@ function dfparser.icon_list(style)
 		for _, prog in ipairs(programs) do
 			if prog.Icon and prog.Exec then
 				local key = string.match(prog.Exec, "[%a%d%.%-_/]+")
-				if string.find(key, "/") then key = string.match(key, "[%a%d%.%-_]+$") end
-				list[key] = prog.icon_path
+				if key then
+					if string.find(key, "/") then key = string.match(key, "[%a%d%.%-_]+$") end
+					list[key] = prog.icon_path
+				end
 			end
 		end
 	end

```

Also, if you do some debug and provide 'problem' desktop file, I can try to fix the issue in a proper way.

**Comment by ChunjieShan** [comment]
It works! Thank you very much!
