### ISSUE TITLE
Missing wallpapers

### ISSUE THREAD

**Issue by arkrost** [worron/awesome-config#5]
Hi, worron! I was wondering if you could share your wallpapers. The one from green theme looks really fantastic.

**Comment by worron** [comment]
Some explanations about wallpapers here. Random art was found in the web, then stylized for personal use. Unfortunately I don't keep the original art, and can say nothing about its authors and license. Thats why wallpaper was not included in repo.

I hope I do nothing blameworthy [leaving the link](https://yadi.sk/d/Vo5OIh_i3HGAvP) without any copyright details.

**Comment by arkrost** [comment]
Thank you very much. I really appreciate your reply.
