### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lunacorn** [worron/awesome-config#51]
Hey worron,

i stumbled upon your work on this project one day and it changed my awesomewm life.
since then i have been curious of the license, you willingness to accept themes built. and also if its okay to repost my personal adjustments on my github through a fork.

still working on my git desktop redflat widget however have created a theme of my own desire. and would love to share the work with you and the community at large.

**Comment by lunacorn** [comment]
equally, what you would like for acknowledgement if the above is solid, happy to do w/e u like so that your work gets credit n shtuffz

**Comment by worron** [comment]
This should be GPLv2 I suppose. Honestly, I start work on it many years ago and wasn't expect scripts ended up so big to require formalizing.

All scripts in  `awesome-config` repo are some kind of personal configs. Feel free to fork it, rework it on any level and share your work among community. Reddit unixporn or GitHub AwesomeWM screenshot thread are good places to showcase your final config, by the way. As it said, this scripts is pretty individual thing, so no need to contribute new themes back to my repo. Leaving the link to the original in readme file would be enough.

On the other hand `redflat` submodule has no personal settings, only core mechanics and general extensions for WM features. If you have any improvement or fixes to `redflat` files I shall give them my best consideration.

**Comment by lunacorn** [comment]
will do, and gladly give credit.  things i was workin on for redflat were several grids of widgets that could be swapped between via hotkey each with own setup and spacing

**Comment by worron** [comment]
Sounds interesting. I'll take a look how it fit to `redflat` If you'll bother to make PR after completing this feature.

Good luck.
