### ISSUE TITLE
Terminal Emulator not showing with Modkey + Return

### ISSUE THREAD

**Issue by Kemwer** [worron/awesome-config#54]
Please, I'm a noob with Windows Managers, there is no terminal showing when pressing modkey + return since install

When I press modkey+F1 and then modkey+return I can see it turning red when I press those keys but nothing happens.
 
I also wanted to use Alacritty as a terminal emulator. Can you help me please?

love your work

**Comment by worron** [comment]
This setup configured to use `urxvt` by default. [Here](https://github.com/worron/awesome-config/blob/54e545a70df9c17d4c95fcb7c16edff6173e2e20/color/blue/env-config.lua#L28) you can setup your own terminal command for colored themes.

**Comment by Kemwer** [comment]
> This setup configured to use `urxvt` by default. [Here](https://github.com/worron/awesome-config/blob/54e545a70df9c17d4c95fcb7c16edff6173e2e20/color/blue/env-config.lua#L28) you can setup your own terminal command for colored themes.

Thank you for the reply, I have urxvt installed, I still changed it to alacritty on the file you pointed out for the color I'm using but nothing, it's weird because everything else works but I have to open the terminal with modkey+r, when I press modkey+return the cursor just blinks, that's it. 

Can I try anything else? 

thank you for the help

**Comment by worron** [comment]
Strange, which config (color) do you use exactly?

Ok, just edit hotkeys directly then. Find keys file for your config (e.x. [blue keys setup](https://github.com/worron/awesome-config/blob/54e545a70df9c17d4c95fcb7c16edff6173e2e20/color/blue/keys-config.lua#L607)), edit `mod4+Return` line to raw launch command.
Something like 
```
{ env.mod }, "Return", function() awful.spawn('urxvt') end,
```
or
```
{ env.mod }, "Return", function() awful.spawn('alacritty') end,
```

**Comment by Kemwer** [comment]
I am using the blue color, but it happened the same with the red one. 

I changed the variable to 'alacritty' on the color keys config file but it didn't work

When I had the default config it used to work, I used alacritty fine. I remember changing it on the rc.lua file but it is not there anymore, do you have any other suggestions? I can open alacritty and urxvt and any program via modkey-r it's just modkey-return that does not work.

**Comment by worron** [comment]
Have no clue then.

Try to do any changes in keys configuration file just to test how it works. Swap some commands or add new one. 
Try to bind to `mod4+Return` any other application to test how `awful.spawn()` work. 
Try to bind `awful.spawn('alacritty')` to any other hotkey.

**Comment by Kemwer** [comment]
I messed up, I had been using colorless thinking it was the blue theme. Changing the env-config.lua file to use alacritty did the trick, thank you for the help!
