### ISSUE TITLE
error with blue version of awesome config

### ISSUE THREAD

**Issue by fallen1011** [worron/awesome-config#6]
Awesome Version 4.1

Choice: Blue Version

3 screen displays 3440x1440 each. 

The tags display the text but then an additional 1-9 tags including the named tags from the config

ACYL is installed, Instructions listed on front page followed. I am not familiar fully with lua, i checked to make sure all paths matched my username and folder. Any Ideas?

![2017-06-13-235041_520x240_scrot](https://user-images.githubusercontent.com/29430595/27131862-9351d270-50da-11e7-97a1-2b01681c9458.png)
![2017-06-14-091856_499x218_scrot](https://user-images.githubusercontent.com/29430595/27134119-91c44660-50e2-11e7-8b27-0125cdba6a61.png)
![2017-06-14-091905_322x25_scrot](https://user-images.githubusercontent.com/29430595/27134120-91c5c008-50e2-11e7-854d-c5daea0c2f96.png)
![2017-06-14-091916_1369x40_scrot](https://user-images.githubusercontent.com/29430595/27134118-91c35c78-50e2-11e7-9333-cd53d9890b9d.png)
![2017-06-14-092514_499x241_scrot](https://user-images.githubusercontent.com/29430595/27134396-6d6c13a0-50e3-11e7-9ac1-c9818a93a297.png)

**Comment by worron** [comment]
I'd recommend `rc-colorless` to try and check if it works without errors.

Colored configs has many specific widgets and required careful fixes for current hardware and software environment. If you still want to proceed with blue config, disable desktop widgets firstly, it should greatly reduce error numbers. Remove this lines
```lua
local desktop = require("blue.desktop-config") -- load file with desktop widgets configuration
desktop:init({ env = env })
```

**Comment by fallen1011** [comment]
that fixed the issue. I ended up going back to my old config. The keybinds, tiling and mouse focus drive me nuts. Was trying to get the mouse to focus windows. Tiling to be automatic and switchable layouts with mod+space. and the killing windows is confusing. window has to be clicked, then mod+c+k+a. way too many keybinds just to kill a window. I also tried switching the app switcher keybinds from mod+shift+a to mod+a and just switch the two around, and it wouldnt work. The UI is nice, but the keybinds are all over the place, it would take too much time to revert the majority of it.

**Comment by worron** [comment]
It seems there was some misunderstanding about this configs.
> Was trying to get the mouse to focus windows

Mouse following focus can be set in `env-config.lua`. 
>Tiling to be automatic

Tiling schemes for every tag can be configured in `*-rc.lua`.
>and switchable layouts with mod+space

There `mod+up`, `mod+down`, `mod+y` by default to switch layout and you can always add `mod+space` by yourself.
> way too many keybinds just to kill a window

`Mod+F4` just to kill a window, while `mod+c+k+a` for kill all on tag.

Let's say straight, it would be miracle if someone's big config fit perfect for for you without fixes. But  all key bindings can be redefined, all widgets can be reconfigured and so on, that how it works.

Feel free to ask anything or close this issue If there are no more questions left.

**Comment by fallen1011** [comment]
i think i was looking in the wrong places. im not used to this style of configs. Most AWM configs have everything in one rc.lua and theme.lua. with what youve listed im starting to understand the layout of the file structure for the color picked and how to edit the lua. 

a few things im a bit confused on, what is the top line bar on a window for? i know you can access the menu, drag a window, or scroll to switch windows. The bar with 3 lines, looks like a close max and minimize to me, but they dont do that is that was the case. what is the main purpose for the bar?

When using mod+r if there are multiple options in the prompt, how do i move down an option? it works fine on colorless, but not on blue.

**Comment by worron** [comment]
>what is the top line bar on a window for?

[Here is](https://github.com/worron/awesome-config/issues/4#issuecomment-295304210) a bit detailed answer.
>When using mod+r if there are multiple options in the prompt, how do i move down an option?

This keys defined in `keys-config.lua` "Apprunner widget" section, check it.
According to my habits I set `mod+i`, `mod+k` for moving. For colorless config new keys was added to default arrow keys
```lua
apprunner:set_keys(awful.util.table.join(apprunner.keys.move, apprunner_keys_move), "move")
```
for blue default keys was overwritten
```lua
apprunner:set_keys(apprunner_keys_move, "move")
```
By the way, use `mod+F1` to get information about current hotkeys.
