### ISSUE TITLE
i need help to get working the applets working on arch linux

### ISSUE THREAD

**Issue by alavaelian** [worron/awesome-config#61]
i can not get working the applets with pipewire neither the update applet or the torrent ones beside that is a great theme boy can you help to get those working

**Comment by worron** [comment]
Sorry, config tuning may be very specific and heavily depend on your system and hardware. Can't help much.

For torrent applet you need `transmission-cli` installed. No clue about other mentioned applets, diggin into code by yourself is only option I'm afraid.

**Comment by alavaelian** [comment]
Thanks for the help dude this is literally the best theme of awesome that i ever seen
